import Head from 'next/head'

import Navb from '../components/Nav'

import Container from 'react-bootstrap/Container';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navb />
      <Container className='layout-container'>
        {children}
      </Container>

    </>
  )
}
export default Layout